source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.3'

gem 'rails', '~> 7.1'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'jwt', '~> 2.8'
gem 'bcrypt', '~> 3.1'
gem 'kaminari', '~> 1.2'
gem 'rack-cors', '~> 2.0'
gem 'rack-attack', '~> 6.7'
gem 'redis', '~> 5.0'
gem 'bootsnap', require: false
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.2'
  gem 'shoulda-matchers', '~> 6.0'
  gem 'database_cleaner-active_record', '~> 2.1'
end

group :development do
  gem 'annotate'
end
